<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- <GenerateDocumentationFile>true</GenerateDocumentationFile> -->
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AssemblyName>MarcoZechner.ColorDotNet</AssemblyName>
    <RootNamespace>MarcoZechner.ColorDotNet</RootNamespace>

    <PackageId>MarcoZechner.Color</PackageId>
    <Authors>Marco Zechner</Authors>
    <RepositoryUrl>https://github.com/...</RepositoryUrl> <!--todo-->
    <PackageLicenseExpression>MIT</PackageLicenseExpression> <!--todo-->
    <Description></Description> <!--todo-->
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyName>ColorDotNet</AssemblyName>
    <RootNamespace>MarcoZechner.ColorDotNet</RootNamespace>
    <PackageId>MarcoZechner.ColorDotNet</PackageId>
  </PropertyGroup>

</Project>
