<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- <GenerateDocumentationFile>true</GenerateDocumentationFile> -->
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>

    <Authors>Marco Zechner</Authors>
    <RepositoryUrl>https://github.com/...</RepositoryUrl> <!--todo-->
    <PackageLicenseExpression>MIT</PackageLicenseExpression> <!--todo-->
    <Description>Lightweight timing and workload metrics (RateMeter, BusyMeter, WorkRate, EventDrivenMetrics).</Description>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyName>Diagnostics.Net</AssemblyName>
    <RootNamespace>MarcoZechner.DiagnosticsDotNet</RootNamespace>
    <PackageId>MarcoZechner.Diagnostics.Net</PackageId>
  </PropertyGroup>

</Project>
