<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET" Version="2.22.0" />
    <PackageReference Include="SkiaSharp" Version="3.116.1" />
    <PackageReference Include="Topten.RichTextKit" Version="0.4.167" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\lib\diagnostics\MarcoZechner.Diagnostics.csproj" />
    <ProjectReference Include="..\lib\color\MarcoZechner.Color.csproj" />
    <ProjectReference Include="..\lib\math\MarcoZechner.Math.csproj" />
  </ItemGroup>

</Project>
